/*!
 * Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * This file was autogenerated by generateSettings.ts. Do NOT modify by hand.
 * To update this file, update the settings in the extension package.json
 * and run `npm run generateSettings` for that extension.
 */

export const amazonqSettings = {
    "amazonQ.telemetry": {},
    "amazonQ.suppressPrompts": {
        "createCredentialsProfile": {},
        "codeWhispererNewWelcomeMessage": {},
        "codeWhispererConnectionExpired": {},
        "amazonQWelcomePage": {},
        "amazonQSessionConfigurationMessage": {},
        "minIdeVersion": {},
        "ssoCacheError": {},
        "amazonQLspManifestMessage": {},
        "amazonQWorkspaceLspManifestMessage": {},
        "amazonQChatDisclaimer": {},
        "amazonQChatPairProgramming": {},
        "amazonQSelectDeveloperProfile": {}
    },
    "amazonQ.showCodeWithReferences": {},
    "amazonQ.importRecommendationForInlineCodeSuggestions": {},
    "amazonQ.shareContentWithAWS": {},
    "amazonQ.workspaceIndexMaxSize": {},
    "amazonQ.workspaceIndexMaxFileSize": {},
    "amazonQ.workspaceIndexIgnoreFilePatterns": {},
    "amazonQ.ignoredSecurityIssues": {},
    "amazonQ.proxy.certificateAuthority": {},
    "amazonQ.proxy.enableProxyAndCertificateAutoDiscovery": {},
    "amazonQ.openAICompatServer.autoStart": {},
    "amazonQ.openAICompatServer.port": {},
    "amazonQ.openaiServer.port": {},
    "amazonQ.openaiServer.autoStart": {},
    "amazonQ.anthropicServer.port": {},
    "amazonQ.anthropicServer.autoStart": {},
    "amazonQ.anthropicServer.retryOnPortBusy": {},
    "amazonQ.anthropicServer.retryIntervalSeconds": {},
    "amazonQ.anthropicServer.dockerEnabled": {},
    "amazonQ.anthropicServer.defaultEnvironmentImage": {},
    "amazonQ.anthropicServer.containerMemoryMb": {}
}

export default amazonqSettings
